import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

import { createUmbod } from '../../src/server/api.ts';
import { makeManifest } from '../helpers.ts';

let tempDir: string;

beforeEach(() => {
	tempDir = mkdtempSync(path.join(tmpdir(), 'umbod-analytics-route-test-'));
});

afterEach(() => {
	rmSync(tempDir, { recursive: true, force: true });
});

async function fetchJson(
	umbod: ReturnType<typeof createUmbod>,
	pathName: string,
	init?: RequestInit
): Promise<unknown> {
	const response = await umbod.fetch(new Request(`http://umbod.test${pathName}`, init));
	if (!response) throw new Error(`route did not handle ${pathName}`);
	expect(response.status).toBe(200);
	return response.json();
}

describe('analytics API routes', () => {
	test('exposes a read-only conservative starter policy draft', async () => {
		const umbod = createUmbod({
			manifest: makeManifest(),
			dbPath: path.join(tempDir, 'draft.db'),
			sessionLogSources: [],
		});
		try {
			await fetchJson(umbod, '/api/evaluate', {
				method: 'POST',
				headers: { 'content-type': 'application/json' },
				body: JSON.stringify({ agent: 'test', tool: 'bash', command: 'git status' }),
			});
			const draft = (await fetchJson(umbod, '/api/policy/draft?limit=100&maxRules=10')) as {
				source: string;
				dataset: { evaluated: number };
			};
			expect(draft.dataset.evaluated).toBe(1);
			expect(draft.source).toContain('DRAFT generated by Umbod');
			expect(draft.source).toContain('operations = ["git.read"]');
		} finally {
			umbod.close();
		}
	});

	test('exposes deterministic policy lint findings without audit writes', async () => {
		const umbod = createUmbod({
			manifest: makeManifest({ rules: { 'git *': 'allow', 'git push *': 'approve' } }),
			dbPath: path.join(tempDir, 'lint.db'),
			sessionLogSources: [],
		});
		try {
			const before = umbod.auditLog.countFiltered();
			const lint = (await fetchJson(umbod, '/api/policy/lint')) as { findings: Array<{ code: string }> };
			expect(lint.findings).toContainEqual(expect.objectContaining({ code: 'shadowed-rule' }));
			expect(umbod.auditLog.countFiltered()).toBe(before);
		} finally {
			umbod.close();
		}
	});
	test('exposes embedded analytics and coverage with injected transcript roots', async () => {
		const transcriptRoot = path.join(tempDir, 'claude');
		const projectDir = path.join(transcriptRoot, '-work-project');
		mkdirSync(projectDir, { recursive: true });
		writeFileSync(
			path.join(projectDir, 'session.jsonl'),
			JSON.stringify({
				type: 'assistant',
				timestamp: '2026-07-10T10:00:00.000Z',
				sessionId: 'session-1',
				cwd: '/work/project',
				message: { content: [{ type: 'tool_use', id: 'toolu-1', name: 'Bash', input: { command: 'git status' } }] },
			})
		);
		const otherProjectDir = path.join(transcriptRoot, '-work-other');
		mkdirSync(otherProjectDir, { recursive: true });
		writeFileSync(
			path.join(otherProjectDir, 'session.jsonl'),
			JSON.stringify({
				type: 'assistant',
				timestamp: '2026-07-10T10:00:00.000Z',
				sessionId: 'session-other',
				cwd: '/work/other',
				message: {
					content: [{ type: 'tool_use', id: 'toolu-other', name: 'Bash', input: { command: 'git status' } }],
				},
			})
		);
		const nestedProjectDir = path.join(transcriptRoot, '-work-project-nested');
		mkdirSync(nestedProjectDir, { recursive: true });
		writeFileSync(
			path.join(nestedProjectDir, 'session.jsonl'),
			JSON.stringify({
				type: 'assistant',
				timestamp: '2026-07-10T10:00:00.000Z',
				sessionId: 'session-nested',
				cwd: '/work/project/nested',
				message: {
					content: [{ type: 'tool_use', id: 'toolu-nested', name: 'Bash', input: { command: 'git status' } }],
				},
			})
		);
		const umbod = createUmbod({
			manifest: makeManifest({
				workspaces: [
					{ id: 'strict-project', roots: ['/work/project'], rules: {} },
					{ id: 'nested-project', roots: ['/work/project/nested'], rules: {} },
				],
			}),
			dbPath: path.join(tempDir, 'audit.db'),
			sessionLogSources: [{ agent: 'claude', rootDir: transcriptRoot }],
		});

		try {
			const evaluation = (await fetchJson(umbod, '/api/evaluate', {
				method: 'POST',
				headers: { 'content-type': 'application/json' },
				body: JSON.stringify({
					agent: 'claude',
					tool: 'bash',
					command: 'git status',
					workingDirectory: '/work/project',
					workspaceId: 'strict-project',
					timestamp: '2026-07-10T10:00:00.000Z',
					sessionId: 'session-1',
					toolUseId: 'toolu-1',
				}),
			})) as {
				entry: { sessionId?: string; toolUseId?: string; resolvedWorkspaceId?: string };
			};
			expect(evaluation.entry).toMatchObject({
				sessionId: 'session-1',
				toolUseId: 'toolu-1',
				resolvedWorkspaceId: 'strict-project',
			});

			const tools = (await fetchJson(umbod, '/api/analytics/tools?since=2026-07-01T00:00:00.000Z')) as {
				totals: { entries: number };
			};
			expect(tools.totals.entries).toBe(1);

			const rules = (await fetchJson(
				umbod,
				'/api/analytics/rules?since=2026-07-01T00:00:00.000Z&workspace=strict-project'
			)) as {
				rules: unknown[];
			};
			expect(rules.rules).toEqual([]);

			const calls = (await fetchJson(
				umbod,
				'/api/analytics/calls?tool=bash&agent=claude&workspace=strict-project&classification=readonly&decision=allow&search=status'
			)) as {
				entries: Array<{ command: string; sessionId?: string; resolvedWorkspaceId?: string }>;
				page: number;
				pageSize: number;
				total: number;
				totalPages: number;
			};
			expect(calls.entries).toEqual([
				expect.objectContaining({
					command: 'git status',
					sessionId: 'session-1',
					resolvedWorkspaceId: 'strict-project',
				}),
			]);
			expect(calls).toMatchObject({ page: 1, pageSize: 50, total: 1, totalPages: 1 });

			const coverage = (await fetchJson(
				umbod,
				'/api/analytics/coverage?since=2026-07-01T00:00:00.000Z&workspace=strict-project'
			)) as {
				coverageRatio: number;
				totals: { sessionCalls: number; matched: number };
			};
			expect(coverage).toMatchObject({ coverageRatio: 1, totals: { sessionCalls: 1, matched: 1 } });
		} finally {
			umbod.close();
		}
	});

	test('requires an exact project for coverage of an id-only workspace', async () => {
		const umbod = createUmbod({
			manifest: makeManifest({
				workspaces: [{ id: 'explicit-only', roots: [], rules: {} }],
			}),
			dbPath: path.join(tempDir, 'audit.db'),
			sessionLogSources: [],
		});

		try {
			const response = await umbod.fetch(
				new Request('http://umbod.test/api/analytics/coverage?workspace=explicit-only')
			);
			expect(response?.status).toBe(400);
			expect(await response?.json()).toEqual({
				ok: false,
				error:
					'workspace "explicit-only" has no roots; coverage requires an exact project because transcripts do not record workspace IDs',
			});
		} finally {
			umbod.close();
		}
	});

	test('supports folded server search, cursor summaries, detail loading, and snapshots', async () => {
		const umbod = createUmbod({
			manifest: makeManifest(),
			dbPath: path.join(tempDir, 'audit.db'),
			sessionLogSources: [],
		});

		try {
			for (const command of ['Grímr inspect', 'smørrebrød make', 'Straße check', 'plain command']) {
				umbod.auditLog.append(
					{
						agent: 'codex',
						tool: 'bash',
						command,
						args: ['--verbose'],
						inputs: { command },
						timestamp: '2026-07-31T12:00:00.000Z',
					},
					{ decision: 'allow', classification: 'readonly', reason: `allowed ${command}` }
				);
			}

			const folded = (await fetchJson(umbod, '/api/analytics/calls?search=STRASSE')) as {
				entries: Array<{ command: string }>;
				page: number;
				total: number;
			};
			expect(folded.entries.map((entry) => entry.command)).toEqual(['Straße check']);
			expect(folded).toMatchObject({ page: 1, total: 1 });

			const first = (await fetchJson(
				umbod,
				'/api/analytics/calls?pagination=cursor&cursor=start&pageSize=2&projection=summary&includeTotal=0'
			)) as {
				entries: Array<Record<string, unknown>>;
				hasMore: boolean;
				nextCursor: string;
				total?: number;
			};
			expect(first).toMatchObject({ hasMore: true });
			expect(first.total).toBeUndefined();
			expect(first.entries).toHaveLength(2);
			expect(first.entries[0]).toEqual({
				id: expect.any(Number),
				agent: 'codex',
				tool: 'bash',
				command: 'plain command',
				timestamp: '2026-07-31T12:00:00.000Z',
				decision: 'allow',
				classification: 'readonly',
			});

			const second = (await fetchJson(
				umbod,
				`/api/analytics/calls?pagination=cursor&cursor=${first.nextCursor}&pageSize=2&projection=summary&includeTotal=true`
			)) as {
				entries: Array<{ id: number; command: string }>;
				hasMore: boolean;
				nextCursor: null;
				total: number;
				totalPages: number;
			};
			expect(second.entries.map((entry) => entry.command)).toEqual(['smørrebrød make', 'Grímr inspect']);
			expect(second).toMatchObject({ hasMore: false, nextCursor: null, total: 4, totalPages: 2 });

			const detail = (await fetchJson(umbod, `/api/analytics/calls/${String(first.entries[0]?.id)}`)) as {
				entry: { args: string[]; inputs: Record<string, unknown>; reason: string };
			};
			expect(detail.entry).toMatchObject({
				args: ['--verbose'],
				inputs: { command: 'plain command' },
				reason: 'allowed plain command',
			});

			const snapshot = (await fetchJson(umbod, '/api/analytics/snapshot?projection=summary')) as {
				tools: { totals: { entries: number }; byTaskType: unknown[]; unusedTools: unknown[] };
				rules: { rules: unknown[]; approvalHotspots: unknown[]; suggestions: unknown[] };
				revision?: string;
			};
			expect(snapshot.tools.totals.entries).toBe(4);
			expect(snapshot.tools.byTaskType).toEqual([]);
			expect(snapshot.tools.unusedTools).toEqual([]);
			expect(snapshot.rules.rules).toEqual([]);
			expect(snapshot.rules.approvalHotspots).toEqual([]);
			expect(snapshot.rules.suggestions).toEqual([]);
			expect(snapshot.revision).toBe(umbod.auditLog.revision());

			const missing = await umbod.fetch(new Request('http://umbod.test/api/analytics/calls/99999'));
			expect(missing?.status).toBe(404);
			const malformed = await umbod.fetch(
				new Request('http://umbod.test/api/analytics/calls?pagination=cursor&cursor=nope')
			);
			expect(malformed?.status).toBe(400);
			const contradictory = await umbod.fetch(
				new Request('http://umbod.test/api/analytics/calls?pagination=page&cursor=1')
			);
			expect(contradictory?.status).toBe(400);
		} finally {
			umbod.close();
		}
	});
});
