import type { ApprovalDecision, StoredAuditEntry } from '../core/types.ts';
import type { AuditLogReader } from '../db/audit-log.ts';
import { inferredOperation } from '../policy/operations.ts';
import { affectedPaths } from '../policy/rule-candidates.ts';
import { matchesPattern } from '../policy/rule-matcher.ts';

export interface StarterPolicyOptions {
	limit?: number;
	maxRules?: number;
	name?: string;
}

export interface StarterPolicyDraft {
	source: string;
	dataset: { eligible: number; evaluated: number; truncated: boolean };
	rules: number;
	tests: number;
	warnings: string[];
}

interface DraftCluster {
	id: string;
	operation?: string;
	tool?: string;
	decision: ApprovalDecision;
	sample: StoredAuditEntry;
	count: number;
}

function safeId(value: string): string {
	return (
		value
			.toLowerCase()
			.replace(/[^a-z0-9]+/g, '-')
			.replace(/^-|-$/g, '')
			.slice(0, 60) || 'observed'
	);
}

function observedDecision(entry: StoredAuditEntry, operation: string | undefined): ApprovalDecision {
	if (entry.classification === 'readonly' || operation === 'git.read' || operation === 'filesystem.read')
		return 'allow';
	return 'approve';
}

function clusterEntries(entries: StoredAuditEntry[], maxRules: number): DraftCluster[] {
	const clusters = new Map<string, DraftCluster>();
	for (const entry of entries) {
		if (
			affectedPaths(entry).some((target) =>
				['**/.env', '**/id_ed25519', '**/*.pem', '**/auth.json'].some(
					(pattern) => matchesPattern(target.path, pattern) || matchesPattern(target.path, pattern.slice(3))
				)
			)
		) {
			continue;
		}
		const operation = entry.operation ?? inferredOperation(entry.tool, entry.command);
		const key = operation ? `operation:${operation}` : `tool:${entry.tool.toLowerCase()}`;
		const existing = clusters.get(key);
		if (existing) {
			existing.count += 1;
			continue;
		}
		clusters.set(key, {
			id: safeId(key),
			operation,
			tool: operation ? undefined : entry.tool.toLowerCase(),
			decision: observedDecision(entry, operation),
			sample: entry,
			count: 1,
		});
	}
	return [...clusters.values()].sort((left, right) => right.count - left.count).slice(0, maxRules);
}

function renderRule(cluster: DraftCluster): string[] {
	return [
		'[[rule]]',
		`id = ${JSON.stringify(`draft-${cluster.id}`)}`,
		`decision = ${JSON.stringify(cluster.decision)}`,
		...(cluster.operation
			? [`operations = [${JSON.stringify(cluster.operation)}]`]
			: [`tools = [${JSON.stringify(cluster.tool)}]`]),
		`reason = ${JSON.stringify(`Draft from ${cluster.count} observed call(s); review before activation`)}`,
		'',
	];
}

function renderTest(cluster: DraftCluster, index: number): string[] {
	const sample = cluster.sample;
	const callFields = [
		`agent = ${JSON.stringify(sample.agent)}`,
		`tool = ${JSON.stringify(sample.tool)}`,
		`command = ${JSON.stringify(sample.command)}`,
		...(cluster.operation ? [`operation = ${JSON.stringify(cluster.operation)}`] : []),
	];
	return [
		'[[test]]',
		`id = ${JSON.stringify(`draft-observation-${index + 1}`)}`,
		`call = { ${callFields.join(', ')} }`,
		`expect = ${JSON.stringify(cluster.decision)}`,
		'',
	];
}

export function generateStarterPolicyDraft(
	auditLog: AuditLogReader,
	options: StarterPolicyOptions = {}
): StarterPolicyDraft {
	const limit = options.limit ?? 2000;
	const maxRules = options.maxRules ?? 25;
	if (!Number.isSafeInteger(limit) || limit < 1 || limit > 100_000) throw new Error('draft limit must be 1..100000');
	if (!Number.isSafeInteger(maxRules) || maxRules < 1 || maxRules > 100)
		throw new Error('draft maxRules must be 1..100');
	const eligible = auditLog.countFiltered({});
	const entries = auditLog.listRecentFiltered({}, limit);
	const clusters = clusterEntries(entries, maxRules);
	const lines = [
		'# DRAFT generated by Umbod from observed behavior.',
		'# Historical approvals are not policy intent. Mutating operations remain approval-gated.',
		'# Review, simulate, lint, and run the embedded tests before activation.',
		'',
		'[env]',
		`name = ${JSON.stringify(options.name ?? 'draft')}`,
		'version = "1.0.0"',
		'timeout = 30',
		'',
		'[policy]',
		'default_unknown = "approve"',
		'approval_method = "web"',
		'',
		'[policy.defaults]',
		'readonly = "allow"',
		'stateful = "approve"',
		'destructive = "approve"',
		'external = "approve"',
		'unknown = "approve"',
		'',
		'[[guard]]',
		'id = "draft-sensitive-files"',
		'decision = "block"',
		'paths = ["**/.env", "**/id_ed25519", "**/*.pem", "**/auth.json"]',
		'reason = "Generated invariant for common credential files"',
		'',
		...clusters.flatMap(renderRule),
		...clusters.flatMap(renderTest),
	];
	return {
		source: `${lines.join('\n')}\n`,
		dataset: { eligible, evaluated: entries.length, truncated: entries.length < eligible },
		rules: clusters.length,
		tests: clusters.length,
		warnings: [
			'Generated output is a draft, not inferred policy intent.',
			'Only readonly operations are promoted to allow; mutations remain approve.',
			...(entries.length < eligible ? ['The observation dataset was truncated.'] : []),
		],
	};
}
